### ISSUE TITLE
Newbie Question: Cannot find module 'meteor/std:accounts-ui'?

### ISSUE THREAD

**Issue by VikR0001** [studiointeract/accounts-ui#30]
I installed accounts-ui using these commands:

```
npm i --save react react-dom react-router
meteor add accounts-password
meteor add std:accounts-ui
npm i --save tracker-component
```

On running, the console shows the following errors:

> Uncaught Error: Cannot find module 'tracker-component/package.json'
> Uncaught Error: Cannot find module 'meteor/std:accounts-ui'

What am I missing?

**Comment by VikR0001** [comment]
Interesting. Via the console, I see that std_accounts-ui is loading. I have a breakpoint set on line 25148, and execution is halting at that breakpoint:

`Line 25148: require("./node_modules/meteor/std:accounts-ui/check-npm.js");`

Now here's the odd thing. That line is looking for the package at

> ./node_modules/meteor/std:accounts-ui/check-npm.js.

But it isn't installed there. In fact, there is no folder called "meteor" in my node_modules folder. std_accounts-ui is currently installed at

> myApp/.meteor/local/build/programs/web.browser/packages/std_accounts-ui.js

How can I install std:accounts-ui in the place where it expects itself to be?

**Comment by timbrandin** [comment]
What version of Meteor are you on? So that I can try to reproduce it during the day or this week.

**Comment by PolGuixe** [comment]
I am getting the same as in https://github.com/studiointeract/accounts-ui/issues/29

You can reproduce it here: https://github.com/Zetoff/trajectory/tree/meteor-and-packages-update

**Comment by VikR1000** [comment]
@timbrandin, I am in Meteor 1.3.1.

**Comment by tjramage** [comment]
I'm also having this issue since updating to 1.3.1.

**Comment by timbrandin** [comment]
@VikR0001 alright, thx.

**Comment by PolGuixe** [comment]
In my case is independent from the Meteor version -1.3 or 1.3.1- , but since the `std:accounts-ui` was updated to 1.1.14. 
std:accounts-ui@1.1.13 works fine.

**Comment by timbrandin** [comment]
Ok, so I'll see with what those two versions differ.

**Comment by raphaelkross** [comment]
@timbrandin Also experiencing this issue - so I'll be waiting for more informations or even better, a fix!

Thank you!

**Comment by xavcz** [comment]
@queso solved it live just few minutes ago cloning the package repo (this one) directly into the `packages` folder of the app.

I tried this way of doing on an app of mine too, no more problems with dependencies! Everything runs fine! That's a way to handle it by now 💯

**Comment by timbrandin** [comment]
I guess we can close then.

**Comment by PolGuixe** [comment]
@timbrandin I don't think that cloning the package to the `/packages` folder is a legit solution.

**Comment by tjramage** [comment]
@PolGuixe – I agree! I've just updated to 1.1.19 and latest tracker-component and still seeing the same issue.

![cannot find module](https://cloud.githubusercontent.com/assets/5517057/14473025/08899c8c-00ee-11e6-8e73-2acb046aad12.png)

**Comment by PolGuixe** [comment]
This is difficult to debug it myself since, if I clone the package to `/packages` then the error disappears.

**Comment by queso** [comment]
I feel like this is a core Meteor issue and likely not anything you are doing... Perhaps time to ping @tmesaday or @benjamn?

**Comment by benjamn** [comment]
The errors about missing `<npm-package>/package.json` files are due to [this code](https://github.com/studiointeract/accounts-ui/blob/cc567a432438b521d9aa3be8bf07d48ce87d1416/check-npm.js#L4-L6) checking for packages that are never otherwise imported in this package or the app. When you don't import a package on the client, it doesn't get bundled into your app at all—hence the missing module errors!

You can make those errors go away by putting
```js
import "react";
import "react-dom";
import "tracker-component";
```
anywhere in your client code. I'm tempted to say `std:accounts-ui` shouldn't be checking those packages unless it imports them, but I suppose there may have been a good reason to check.

@tmeasday Perhaps the absence of a `package.json` file should be a sign that the package is never used, and therefore its version doesn't matter?

**Comment by tmeasday** [comment]
So this issue was partly caused by an error in `check-npm-versions`' detection of missing modules on the client (fixed by https://github.com/tmeasday/check-npm-versions/commit/f50c9860d820b856c353e93590a3cf33339ea2b8, @benjamn what do you think about my janky string matching; do you have a better idea?)

If you update to `tmeasday:check-npm-versions@0.3.1` you should see a more informative error message (although maybe it's not that much more useful).

Ultimately though @benjamn is right, the package should import the things it's checking I suspect.

**Comment by tmeasday** [comment]
> Perhaps the absence of a package.json file should be a sign that the package is never used, and therefore its version doesn't matter?

I'm not sure this makes sense; what if the user has legitimately forgotten to install the npm package? How can we distinguish on the client?

**Comment by SachaG** [comment]
Running into the same issue, I'll downgrade back to 1.1.12 for now.

**Comment by timbrandin** [comment]
I'm not sure how to handle this @SachaG, would it work better without `tmeasday:check-npm-versions`?

**Comment by timbrandin** [comment]
Btw @benjamn I've noticed that if you update a local package in for example another folder, the local built package inside the app doesn't update and get the new node_modules if they where updated, is that a bug with meteor?

**Comment by SachaG** [comment]
@timbrandin I guess? I'm not super clear on what's causing the issue but we can probably not use that package for now?

**Comment by timbrandin** [comment]
Yeah, seems like it works better for me on a clean app installation, anyone want to check out the `devel` version I've pushed, you could just clone it into `/packages` to try it out.

**Comment by PolGuixe** [comment]
Release 1.1.20 seems to be working fine. 

Great job!

**Comment by timbrandin** [comment]
Awesome. I'll close this then.

**Comment by SachaG** [comment]
Has this issue actually been fixed? I was using 1.2.6 and just ran into it again.

**Comment by raphaelkross** [comment]
@SachaG - perhaps deleting the node_modules, checking the versions at package.json and running npm install again remove any cache problem.

**Comment by limratana** [comment]
I came across this issue and benjamn's solution seems to have solved the problem for me.

**Comment by Sburke0708** [comment]
I am still hitting this issue. @benjamn importing `tracker-component` into my ui code doesn't seem to help :(
